### ISSUE TITLE
TypeError: paper.safari is not a function

### ISSUE THREAD

**Issue by lowwa132** [neveldo/jQuery-Mapael#59]
On each hover (in / out), I get this error : TypeError: paper.safari is not a function
Line 976 and 988.

Mapael 1.0.1
Raphaël 2.1.4
Firefox 37.0.2

**Comment by neveldo** [comment]
Hello,

Thank for your bug report. It seems that a non-backward compatible change has been introduced since Raphael.js 2.1.3 as the paper.safari() function has been removed from the API.

I will upgrade jquery mapael with Raphael.js 2.1.4 very soon, and I will come back to you when it's done.

**Comment by neveldo** [comment]
Hello,

I think I answered too fast. the removal of  paper.safari() function is further than the version 2.1.4 of Raphaël. I think you have downloaded the master branch of Raphaël, you should download it from the released packages :  https://github.com/DmitryBaranovskiy/raphael/releases , everything seems to work fine with Raphael 2.1.4.

**Comment by lowwa132** [comment]
You are right. I've downloaded the 2.1.4 version from the master branch. Everything is ok with the release package :+1:

**Comment by neveldo** [comment]
I'm glad it helped you !
